### ISSUE TITLE
500 when installed along with "Close Issue button" plugin

### ISSUE THREAD

**Issue by vasamaximov** [f0y/redmine_private_wiki#12]
Steps to reproduce:
- install the latest Close issue button plugin:
   http://www.redmine.org/plugins/redmine_close_button
- try any URL in your Redmine installation: everything should work fine
- install Private wiki plugin
- rry any URL: it will rerurn "Internal error"

in production.log we have:

```
Started GET "/issues/668" for 91.76.115.167 at 2012-09-06 00:51:09 +0400
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"668"}
  Rendered issues/_action_menu.html.erb (11.5ms)
  Rendered plugins/redmine_close_button/app/views/issues/_close_button.html.erb (1.4ms)
  Rendered issue_relations/_form.html.erb (2.7ms)
  Rendered issues/_relations.html.erb (6.2ms)
  Rendered issues/_history.html.erb (51.4ms)
  Rendered issues/_action_menu.html.erb (3.4ms)
  Rendered issues/_form_custom_fields.html.erb (0.5ms)
  Rendered issues/_attributes.html.erb (34.3ms)
  Rendered issues/_form.html.erb (52.0ms)
  Rendered attachments/_form.html.erb (3.4ms)
  Rendered issues/_edit.html.erb (130.1ms)
  Rendered issues/_sidebar.html.erb (6.6ms)
  Rendered watchers/_watchers.html.erb (69.1ms)
  Rendered issues/show.html.erb within layouts/base (428.1ms)
Completed 500 Internal Server Error in 1006ms

ActionView::Template::Error (Missing partial hooks/html_header with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb, :rjs]}. Searched in:
  * "/redmine/plugins/redmine_close_button/app/views"
  * "/redmine/app/views"
):
    18:       body {behavior: url(<%= stylesheet_path "csshover.htc" %>);}
    19:     </style>
    20: <![endif]-->
    21: <%= call_hook :view_layouts_base_html_head %>
    22: <!-- page specific tags -->
    23: <%= yield :header_tags -%>
    24: </head>
  lib/redmine/hook.rb:110:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:151:in `call_hook'
  app/views/layouts/base.html.erb:21:in `_app_views_layouts_base_html_erb__4075490176800572136_42316900'
  app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in `show'
```

**Comment by f0y** [comment]
What is  the version of Redmine? 1.3?

**Comment by vasamaximov** [comment]
```
Environment:
  Redmine version                          2.0.2.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.5
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_close_button                     0.0.8
```

**Comment by f0y** [comment]
I've installed close_button plugin and it works well with private_wiki plugin. I think the cause is not related to private_wiki plugin. Furthermore, there is nothing in close_button plugin that might conflict.
